version: '3.8'
services:

    mongo:
        image: 'mongo'
        container_name: mongodb
        ports:
            - '27017:27017'
        restart: unless-stopped

    web:
        container_name: sayollo
        build: .
        volumes:
            - .:/app/
        command: uvicorn main:app --host 0.0.0.0
        ports:
            - 8000:8000
        environment:
            - MONGODB_URL=mongodb://mongo:27017
        depends_on:
            - mongo
